# mysql
mysql:
  url: "sqlite:///data/xiaoluobo.db"

headers:
  X-LC-Sign: "a339730b45da36e66c2c3ddd0365191a,1753283506441"
  # 固定值
  X-LC-Session: "elkwkwh7fo2cydt0d51s46x9p"
  # 固定值
  X-LC-Id: "6IkiQ1QmPKMayoS8DKVi7067-gzGzoHsz"

email:
  sendEmail: "newsepoch@163.com"
  sendPass: "MFS33kEx8XwRSuvY"
  sendHost: "smtp.163.com"
  acceptEmail: "819730159@qq.com"
dingding:
  url: "https://oapi.dingtalk.com/robot/send?access_token=684d6cb7bc2cca28d8637656dbed6f0e67f4e3811b3a2b4dc5de3c2de0c1e37e"